### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/K2NN#2]
1. What is "size" in this context? is it that there are **10,000;** rows/vectors with 64 bit values in each one? (each of the 10,000 has 64 0 or 1 values?)  I'm confused how you mention that it's suitable for 512 but the 512 value is not used here (Or I really don't understand C++)

```
	// ------------- Generation of Random Data ------------
	// obviously, this is not representative of real data;
	// it doesn't matter for brute-force matching
	// but the MIH methods will be much faster
	// on real data
	void *qvecs = malloc(64 * size), *tvecs = malloc(64 * size);
	srand(36);
	for (int i = 0; i < 64 * size; ++i) {
		reinterpret_cast<uint8_t*>(qvecs)[i] = static_cast<uint8_t>(rand());
		reinterpret_cast<uint8_t*>(tvecs)[i] = static_cast<uint8_t>(rand());
	}
	// --------------------------------

```

2. After matching, the m.matches contains an array of **Match**, how does that _Match_ relate back to the _tvecs_ ?

`  std::cout << std::endl <<  m.matches[34].q  << std::endl;` gives me the output of 242 (the 34 just a random number)

```
Warming up...
Testing...

242

Brute force K2NN found 1334 matches in 100.403 ms
Throughput: 0.995982 billion comparisons/second.
```

So what is that 242? is it an index so that like it would be `tvecs[242]` ?

So for example, if I loaded 2 sets of binary descriptors with 200 descriptors per set - it would have to scan 400 binary descriptors, 242 would mean its the 42nd descriptor of the 2nd set?

**Comment by komrad36** [comment]
Hey,

So as the README says, "brute-force and a custom Multi-Index Hash Table accelerator system for matching 512-bit binary descriptors".

So each descriptor is 512 bits in length. This plays well with the rest of my faster-than-previous-state-of-the-art computer vision pipeline stuff, like LATCH/ULATCH/CLATCH/UCLATCH, that's why I'm focused on 512-bit at the moment.

size is the number of such descriptors.

512/8 = 64 bytes each, which is why the allocations are for 64 * size.

So after matching, you have a std::vector<Match>. The Match struct contains two integers: q, and t. These are the _indices_ of the matches. For example, if you have a Match struct with q = 10 and t = 15, that means the 11th query descriptor has been found to match with the 16th training descriptor.

I should mention that the brute-forcer is mainly an easily verifiable reference solution. It's fast for CPU, but that's not saying much. CUDAK2NN achieves 54 billion (!!) comparison per second on a stock GTX 1080.

The main point of K2NN is actually the experiment with multi-index hashing. The jury is still out on whether that's worth it. My money says no given how insanely fast I was able to make CUDAK2NN. Sometimes you really can just steamroll time complexity with brute force. For very large datasets, perhaps the time complexity would come back to bite you and multi-index hashing might be worth it. I suspect that's particularly true for small (maybe 64-bit) descriptors.

Thanks!

**Comment by dgtlmoon** [comment]
Perfect!! Thanks!!
