### ISSUE TITLE
Please document 'size' parameter

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/K2NN#4]
```
// Matcher<false> m(tvecs, size, qvecs, size, threshold, max_twiddles);
```

And for extra points, if you could kindly clarify `threshold`, is that the popcount difference (in %?) or the sum of hamming distance difference between any two 512bit binary descriptors?

**Comment by dgtlmoon** [comment]
So the thing for me is - why is there `size` twice here?

```

// Example initialization of Matcher class
// Matcher<false> m(tvecs, size, qvecs, size, threshold, max_twiddles);
//
// Options:
```

**Comment by dgtlmoon** [comment]
Apologies...

```
	// Number of training vectors
	int tcount;

	// Incoming 512-bit query vectors
	const void* __restrict qset;

	// Number of query vectors
	int qcount;
```

**Comment by komrad36** [comment]
Yep, documentation at the parameters rather than the arguments! I agree with you that the use of 'size' to describe both vector sizes in the main.cpp is ambiguous and should be separated out. I'll do that at some point. The main.cpp is just a test driver that I threw together very quickly, and all the actual engineering effort, including proper documentation, is in LATCH.h. But I'll work on cleaning up main.cpp as well. Thanks!

> And for extra points, if you could kindly clarify threshold, is that the popcount difference (in %?) or the sum of hamming distance difference between any two 512bit binary descriptors?

Sure! From the README:

> a match is returned if the best match between a query vector and a training vector is more than a certain threshold number of bits better than the second-best match. Yes, that means the DIFFERENCE in popcounts is used for thresholding, NOT the ratio. This is the CORRECT approach for binary descriptors.

I know this can be confusing to people unfamiliar with 2NN, and it takes a surprising amount of effort to explain in English words. I sent you that long email with a proper explanation. For anyone else who might end up reading this thread, I'll reproduce my full explanation from that email:

> So we have descriptions of all the interesting features in each image: for each feature in the first image (which we call the **training**), we want a way to find which corner, if any, from the second image (which we call the **query**), is a different view of the same physical thing. Let's take our first training feature for example. How do we find which query feature, if any, matches? The naive but wrong way to do this is to compare all the query descriptors against the training descriptor, and consider it a match if it differs by less than some threshold number of bits, say 50. In technical terms we consider it a match if the Hamming distance is less than 50. This is bad. That's because comparison should never be absolute, only relative. Imagine if you get 100 good matches this way. Then in the next frame the camera is bumped a little so the features are a bit blurry. All the matches drop in quality, and you now get 0 matches. But the matches are still exactly the same relative to each other; they've just all dropped in absolute quality. You could still get good results if you had just done relative comparison instead of absolute. So: instead, the right approach is to find the best and second-best matches to the training descriptor. Then don't do an absolute comparison between the query and training; it doesn't matter. Instead, consider the best match to be a match, if its Hamming distance to the training descriptor is less than the second-best match's Hamming distance to the training descriptor by at least some threshold. I know that's confusing but there's no other way to explain the technical process. Make sure it makes sense. This may help: a nontechnical and intuitive explanation of that process and why it works. Instead of considering a query descriptor a match if it's significantly similar to the training descriptor, consider a query descriptor a match if it is a significantly _better_ match than any other query descriptor. Anyway, so that's second-nearest-neighbor, or 2NN, matching, and why it works. That's what K2NN and CUDAK2NN do. Oh, also, notice I use the number of bits by which they differ, i.e. the difference in Hamming distances, and not the ratio of Hamming distances. Punch anyone who tells you you should use the ratio test in the face. They don't know what they're talking about.

So the threshold is _not_ the maximum Hamming distance from Q to T for T to be considered a match; that would be nearest-neighbor matching, and we're doing second-nearest-neighbor (2NN) matching.

Therefore, the threshold is the minimum amount by which the best-matching T's Hamming distance to Q must exceed the second-best-matching T's Hamming distance to Q, for the best-matching T to be considered a match with Q.

Make sense? :D

Hope that helps!
-Kareem

**Comment by dgtlmoon** [comment]
yes, so lets assume I have 8 bit descriptors for argument sake as my training data

```
00111111
00000001
00000000
```

And my query is `00001111` and with a `threshold` of `1`, I can expect to see 

```
00111111
```

I think this is correct

**Comment by komrad36** [comment]
Using an example is a great idea! I should have thought of that for helping explain. Thanks!

Let's see... okay, not quite. So taking your example, we have training:

```
00111111
00000001
00000000
```

And query of `00001111`. Okay, this means the Hamming distances, in order, will be:

`2
3
4`

The best match (index 0), then, has a Hamming distance of 2. The second-best match (index 1) has a Hamming distance of 3. Therefore the best match beats the second-best match by 1 (a.k.a. the **difference** is 1.) The threshold is 1. 1 is not greater than 1, so **no match would be returned**.

Let's take another example. same training set, but a query of `01111111`. Now the Hamming distances are:

`1
6
7`

The best match has a Hamming distance of 1. The second-best match has a Hamming distance of 6. The difference is 5. 5 is greater than 1 so **index 0 would be returned**, since the best match is at index 0.

**Comment by komrad36** [comment]
Remember that we aren't just returning the best match if it's less than `threshold `away; instead, we return the best match if it beats the second-best match by more than `threshold`.

**Comment by komrad36** [comment]
It's sort of like getting a signal-to-noise ratio. What does it matter if this training is only 3 away, if there are 10 other trainings that are only 3 away? Only one of them can be correct, so that by definition means we don't have a reliable match. However, even if this training is 30 away, if the next-best match is 200 away, we can be pretty confident that's a match. That's why we use this second-order approach.
