### ISSUE TITLE
When qvecs and tvecs are the same, there are no results

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/K2NN#6]
I set the byte vector to 255 (b11111111)

```
diff --git a/main.cpp b/main.cpp
index 8e80285..574ab25 100644
--- a/main.cpp
+++ b/main.cpp
@@ -76,8 +76,8 @@ int main() {
        void *qvecs = malloc(64 * size), *tvecs = malloc(64 * size);
        srand(36);
        for (int i = 0; i < 64 * size; ++i) {
-               reinterpret_cast<uint8_t*>(qvecs)[i] = static_cast<uint8_t>(rand());
-               reinterpret_cast<uint8_t*>(tvecs)[i] = static_cast<uint8_t>(rand());
+               reinterpret_cast<uint8_t*>(qvecs)[i] = 255;
+               reinterpret_cast<uint8_t*>(tvecs)[i] = 255;
        }
        // --------------------------------

```

Brute force K2NN found 0 matches in 100.563 ms
Throughput: 0.994399 billion comparisons/second.

**Comment by dgtlmoon** [comment]
I think this is OK because then it would be hard to return that vector of Match if all results were in all results, still worth noting

**Comment by komrad36** [comment]
Yeah, this is expected behavior. Consider what happens if you have even a perfect match, but there are two of them in training:

Training:
00001111
00001111

Query:
00001111

Hamming distances, in order:
0
0

Best match: 0
Second-best match: 0

The difference between the best and second-best matches is 0, which is not greater than the threshold, so no match is returned.

Why do I match this way? Surely a perfect match should always be considered a match?

Well, no. Imagine if you had two very similar-looking features in your frames, such that they had the same descriptor. Let's say the query frame has the same features, so for either query descriptor, _both_ training descriptors are a perfect match. But which one is the correct one? There is no way to reliably select the feature that actually corresponds to the match, so both query descriptors will be discarded. This way, we end up with only features that have _reliable_ matches, i.e. the best match has a very high probability of being the correct match because it's a much _better_ match than its next closest competitor. This is much more important than how good the match is in absolute terms.

Example of this sort of matching at work using CLATCH:
![latch](https://cloud.githubusercontent.com/assets/13008770/21061137/16e961d4-be19-11e6-8ade-6e5d230aa78b.png)

**Comment by komrad36** [comment]
Oh, I should also explain something:

"There is no way to reliably select the feature that actually corresponds to the match."

This matters because typically you're trying to determine 2-D points in both frames that correspond to the _same_ point in 3-D, giving you information that you can later use to determine camera pose. If you're just seeing whether there's any common imagery between the two frames, I can see why this form of matching might be unintuitive, and, in fact, standard boring matching might actually work okay. I could make a version of K2NN that does first-order matching if you want. It would not be a difficult modification.

**Comment by komrad36** [comment]
Okay, latest commit adds first-order matching for `bruteMatch`. Calling like before (`bruteMatch()`) is unaffected. Call like this: `bruteMatch(true)` to get first-order behavior.

**Comment by komrad36** [comment]
If you test it on the random data, keep in mind that the Hamming distance of two random 512-bit descriptors tends to cluster pretty tightly around 256, so you'll probably need a threshold of about 200 or even higher before you get any matches at all in first-order mode.

**Comment by dgtlmoon** [comment]
Yup perfect, so I can confirm that first-order is working as you say, thanks a million!

Tweaking `threshold` on the LATCH generated descriptor works exactly how I would expect first-order matching to work, I think this algorithm will help a _lot_ of people, not just in the image processing realm!
